apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-file-config-component-deployment
  labels:
    package: template
spec:
  replicas: 1
  selector:
    matchLabels:
      component: template-new-file-config-component
  template:
    metadata:
      labels:
        component: template-new-file-config-component
    spec:
      initContainers:
        - name: template-check-openhim-core-status
          image: busybox:1.28
          command: ['sh', '-c', 'until telnet openhim-core-service 8082; do echo OpenHIM Core API not running yet; sleep 10; done;']
      containers:
        - name: template-new-file-config-component
          image: jembi/configurable-canned-response-server:latest
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: "100Mi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "1"
          volumeMounts:
            - name: template-new-file-component-configmap
              mountPath: /home/node/app
      volumes:
        - name: template-new-file-component-configmap
          configMap:
            name: template-new-file-component-configmap
