apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-file-config-component-deployment
  labels:
    package: template
spec:
  replicas: 1
  selector:
    matchLabels:
      component: template-new-file-config-component
  template:
    metadata:
      labels:
        component: template-new-file-config-component
    spec:
      containers:
        - name: template-new-file-config-component
          image: jembi/configurable-canned-response-server:latest
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: "100Mi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "1"
