services:
  config:
    image: commcarehq_incl:latest
    privileged: true  # allows mount inside container
    depends_on:
      - postgres
      - couch
      - redis
      - elasticsearch2
      - kafka
      - zookeeper
      - minio
    volumes:
      - shared_files:/sharedfiles
    command: 'docker/init-hq.sh'

  formplayer:
    extends:
      file: docker-compose.yml
      service: formplayer

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  couch:
    extends:
      file: docker-compose.yml
      service: couch

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  elasticsearch2:
    extends:
      file: docker-compose.yml
      service: elasticsearch2

  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  zookeeper:
    extends:
      file: docker-compose.yml
      service: zookeeper

  minio:
    extends:
      file: docker-compose.yml
      service: minio

volumes:
  shared_files:
