cluster.name: instant_hq
network.host: 0.0.0.0
http.port: 9200

# dev-only setting to allow client-side ES front-ends
http.cors.allow-origin: "*"
http.cors.enabled: true
index.max_result_window: 1000000

action.auto_create_index: false
